Updated onion profile photo for Jane's Onions
codebase-berkeley/cofed pull request #26
Opened 2020-11-03 05:34 UTC by jxnelee

<img width="994" alt="Screen Shot 2020-11-02 at 9 33 01 PM" src="https://user-images.githubusercontent.com/66141423/97952687-28dd1280-1d53-11eb-8304-f0570b024a9d.png">

- added onion.png to assets folder
- changed Jane's Onions' photo from "tina" to "onion"

2020-11-03 07:23 UTC, rrrliu requested changes
THE ONION SO CUTE. also can u add a quick mission :o

2020-11-03 21:54 UTC, leebianca approved these changes, later dismissed

2020-11-03 23:49 UTC, rrrliu reviewed
looks like `.DS_Store` is still here (check the files changed tab). try `git rm .DS_Store`. also pull from `main`. Other than looks good!

2020-11-04 01:27 UTC, rrrliu approved these changes
amazing

2020-11-07 10:21 UTC, merged