added new zaid's chickens profile pic and info
codebase-berkeley/cofed pull request #30
Opened 2020-11-03 20:28 UTC by ZaidMamsa

2020-11-03 20:31 UTC, rrrliu requested changes
LMAO excellent picture choice
1. don't check in .DS_Store
2. fix merge conflicts with `git pull origin/main` on your branch

2020-11-03 22:12 UTC, leebianca approved these changes, later dismissed

2020-11-03 23:45 UTC, rrrliu requested changes
remove the yarn metadata under `cofed/` (remember to run everything under `cofed/client/`)

2020-11-03 23:45 UTC, rrrliu commented on node_modules/.yarn-integrity
> +}
`git rm -r` the node_modules directly under cofed

2020-11-03 23:45 UTC, rrrliu commented on yarn-error.log
> +  # yarn lockfile v1
remove this

2020-11-03 23:45 UTC, rrrliu commented on yarn.lock
> +
remove

2020-11-05 01:03 UTC, rrrliu approved these changes
🥚 🐣 🐥 🐤 🐔 🍗

2020-11-07 10:17 UTC, merged