Endpoint and coop starring
codebase-berkeley/cofed pull request #40
Opened 2020-11-15 10:07 UTC by Claire-Thib

- implemented css for toggling between starred coops and non-starred coops
- stars are rendered correctly
- implementation of toggling starred attribute of coop does not work yet

Our Error:
- line 308 of FiltersPage, we pass in a function toggleStar as a prop. Profile.js is reading that prop as null and FiltersPage is calling toggleStar on its own

2020-11-15 21:33 UTC, leebianca requested changes
you guys 🥺🥺 y'all have come so far ❤️ great job on this task this week! ik it wasn't easy

i left a few comments, and to address your issue with `toggleStar`, you're setting it as a state when it doesn't need to be set as a state. if y'all get rid of the `handleStar` state and fix the comment about `props.handleStar`, that should fix it. on a higher level though, since "starring" is a feature on the profile page, shouldn't the `toggleStar` function be contained within `Profile.js`? what were y'alls reasoning for putting it in `FiltersPage`?

otherwise, it's looking good so far!!

2020-11-15 21:33 UTC, leebianca commented on client/src/components/Profile/Profile.js
> +        <svg className="profile-not-starred" viewBox="0 0 20 20" onClick={() => handleStar(coopId, starrerId)}>
use `props.handleStar` instead. we don't need to be setting `props.handleStar` as a state in order to use it

2020-11-15 21:33 UTC, leebianca commented on client/src/pages/FiltersPage/FiltersPage.js
> +      console.log("HERE")
remove

2020-11-15 21:33 UTC, leebianca commented on client/src/pages/FiltersPage/FiltersPage.js
> +
remove

2020-11-15 21:33 UTC, leebianca commented on client/src/pages/FiltersPage/ReactToggle.css
> +} */
remove

2020-11-15 21:33 UTC, leebianca commented on client/src/components/Profile/Profile.js
> +            {renderStar()}
it seems like the star is stretching out `profile-text-container` and making the contact links clickable way to the right. adding `width: fit-content` to `profile-co-op-contact-link` should fix it

2020-11-15 21:33 UTC, leebianca commented on client/src/components/Profile/Profile.js
> +    console.log("HANDLE STAR: " + props.h)
remove

2020-11-15 21:54 UTC, rrrliu requested changes
gjgj 🤩 !!! look at my comments for advice on how to debug the starring/unstarring API request

also make sure to run `yarn run lint`

2020-11-15 21:54 UTC, rrrliu commented on .vscode/settings.json
> +}
don't check in changes in `.vscode/`

2020-11-15 21:54 UTC, rrrliu commented on client/src/components/Card/Card.js
> +          <path d="M17.684,7.925l-5.131-0.67L10.329,2.57c-0.131-0.275-0.527-0.275-0.658,0L7.447,7.255l-5.131,0.67C2.014,7.964,1.892,8.333,2.113,8.54l3.76,3.568L4.924,17.21c-0.056,0.297,0.261,0.525,0.
same here

2020-11-15 21:54 UTC, rrrliu commented on db/cofed.sql
> +    (6, 1);
newline at end of file

2020-11-15 21:54 UTC, rrrliu commented on db/index.js
> +
remove

2020-11-15 21:54 UTC, rrrliu commented on client/src/pages/FiltersPage/FiltersPage.js
> +
remove

2020-11-15 21:54 UTC, rrrliu commented on client/src/pages/FiltersPage/FiltersPage.js
> +      console.log("HERE")
remove

2020-11-15 21:54 UTC, rrrliu commented on client/src/components/Profile/Profile.js
> +    setHandleStar(props.handleStar);
if these are never changed within the Profile component, they should just remain props. don't create a state for them

2020-11-15 21:54 UTC, rrrliu commented on api/routes/index.js
> +      [request.body.starredId, request.body.starrerId]
`request` doesn't exist in this context (check the parameters of this callback) -- you should be able to use `starrerId` and `starredId` that you declared above

2020-11-15 21:54 UTC, rrrliu commented on client/src/components/Card/Card.js
> +          <path fill='#ffc011' d="M9.5 14.25l-5.584 2.936 1.066-6.218L.465 6.564l6.243-.907L9.5 0l2.792 5.657 6.243.907-4.517 4.404 1.066 6.218"> </path>
move to its own .svg file

2020-11-15 21:54 UTC, rrrliu commented on api/routes/index.js
> +      `INSERT INTO stars (starred_coop_id, starrer_coop_id))
sql syntax error here (check the parentheses)

2020-11-15 21:54 UTC, rrrliu commented on client/src/pages/FiltersPage/FiltersPage.js
> +        },
again, if you're using a an additional data key, make sure you properly handle that in your router.post

2020-11-15 21:54 UTC, rrrliu commented on client/src/pages/FiltersPage/FiltersPage.js
> +        },
this body format doesn't match what your router.delete handler expects, which is another reason it's not working. why is there a `data` key, and make sure the keys match. it looks like you're putting `starred_coop_id` here but your router.delete handler is expecting `starredId`

2020-11-15 22:39 UTC, ilyues commented
> since "starring" is a feature on the profile page, shouldn't the `toggleStar` function be contained within `Profile.js`? what were y'alls reasoning for putting it in `FiltersPage`?

toggleStar changes the array of starred coop ids & both Card.js and Profile.js take in props that use this array - is there a way to change this array from inside Profile.js without passing in a function to change it?

2020-11-16 02:13 UTC, leebianca commented
> > since "starring" is a feature on the profile page, shouldn't the `toggleStar` function be contained within `Profile.js`? what were y'alls reasoning for putting it in `FiltersPage`?
> 
> @leebianca toggleStar changes the array of starred coop ids & both Card.js and Profile.js take in props that use this array - is there a way to change this array from inside Profile.js without passing in a function to change it?

oh yea, in that case, you could use [callback functions](https://webomnizz.com/change-parent-component-state-from-child-using-hooks-in-react/) to change states in the parent component from the child component. just questioning the design decision though :) feel free to just leave it there if it's easier

2020-11-16 06:49 UTC, rrrliu commented on client/src/assets/starred.svg
> +</svg>
add newline

2020-11-16 06:49 UTC, rrrliu commented on client/src/assets/unstarred.svg
> +</svg>
add newline

2020-11-16 06:50 UTC, rrrliu commented on db/index.js
> +
remove

2020-11-16 07:19 UTC, rrrliu approved these changes, later dismissed

2020-11-16 07:44 UTC, leebianca approved these changes, later dismissed

2020-11-18 08:12 UTC, closed without merging