Authentication
codebase-berkeley/cofed pull request #45
Opened 2020-11-22 09:44 UTC by ZaidMamsa

## Motivation

Motivation: high. Maybe 1 week left!

Fixes # 35, session-based authentication

## Summary of Changes

Feel free to use sentences or a bulleted list.

- Create new session for user upon correct login information input
- Ensured authentication for profile and filterpage
- Hashed password and compared to non-hashed input
- Ended user session upon logout
- Authenticated and redirected accordingly to register page

## Testing

N/A. No need 😎

2020-11-22 22:48 UTC, leebianca requested changes
OMG YAY proud of you guys for figuring out authentication! just left a few minor comments here and there but for the most part, looks GOOD

2020-11-22 22:48 UTC, leebianca commented on api/routes/auth.js
> +const saltFactor = 10;
nit: by convention, constant identifiers are in uppercase so just change to `const SALT_FACTOR = 10`

2020-11-22 22:48 UTC, leebianca commented on api/passport-config.js
> +      let hashpass = user.hashed_pass; //await bcrypt.hash(user.hashed_pass, saltFactor);
remove comment from this line

2020-11-23 05:28 UTC, rrrliu requested changes

2020-11-23 05:28 UTC, rrrliu commented on api/app.js
> +// app.use('/auth', authRouter);
remove

2020-11-23 05:28 UTC, rrrliu commented on api/app.js
> +// }
remove

2020-11-23 05:28 UTC, rrrliu commented on api/passport-config.js
> +      // in fact, just delete the INSERT INTO lines in cofed.sql and make your own users
remove

2020-11-23 05:28 UTC, rrrliu commented on api/passport-config.js
> +        console.log('INCORRECT PASS: ' + user.hashed_pass);
pls remove

2020-11-23 05:28 UTC, rrrliu commented on api/passport-config.js
> +    return done(err, null);
I think it’s just done(err)

2020-11-23 05:28 UTC, rrrliu commented on api/routes/auth.js
> +      // let salt = await bcrypt.genSalt(saltFactor);
rm

2020-11-23 05:28 UTC, rrrliu commented on client/src/App.js
> +          path="/profilepage"
actually, we can just delete this route because we’re not using it

2020-11-23 05:28 UTC, rrrliu commented on api/routes/auth.js
> +    const email_query = await db.query(
nit: camelCase please

2020-11-23 05:28 UTC, rrrliu commented on api/routes/index.js
> +  const { email, name, addr, hashed_pass } = req.body;
nit: camelCase hashed_pass -> hashedPassword (make sure to change on frontend as well)

2020-11-23 05:28 UTC, rrrliu commented on client/src/components/Navbar/Navbar.js
> +  } else {
nit: remove else

2020-11-23 05:28 UTC, rrrliu commented on client/src/pages/LoginPage/LoginPage.js
> +      console.log(err.stack);
rm

2020-11-23 05:28 UTC, rrrliu commented on client/src/pages/ProfilePage/ProfilePage.js
> +        console.log(err.stack);
rm

2020-11-23 05:28 UTC, rrrliu commented on client/src/pages/RegisterPage/RegisterPage.js
> +  } else {
nit: rm else

2020-11-23 05:28 UTC, rrrliu commented on client/src/components/Navbar/Navbar.js
> +      console.log(err.stack);
rm

2020-11-23 05:28 UTC, rrrliu commented on client/src/pages/FiltersPage/FiltersPage.js
> +      console.log(err.stack);
rm

2020-11-23 06:00 UTC, rrrliu approved these changes, later dismissed

2020-11-25 08:27 UTC, rrrliu requested changes
last few fixes

2020-11-25 08:27 UTC, rrrliu commented on db/cofed.sql
>      (2, 1),
we don't have any coops, so delete these

2020-11-25 08:27 UTC, rrrliu commented on client/src/pages/FiltersPage/FiltersPage.js
> -    if (res.data.length !== 0) {
keep this `if (res.data.length !== 0)` condition

2020-11-26 04:44 UTC, rrrliu approved these changes

2020-11-26 04:44 UTC, leebianca approved these changes

2020-11-26 04:51 UTC, merged