Autocomplete
codebase-berkeley/cofed pull request #50
Opened 2020-11-29 08:58 UTC by ZaidMamsa

## Motivation

Implement autocompleting location on RegisterPage and ProfilePage and geocoding latitude and longitude coordinates.

Fixes #43 

## Summary of Changes

Feel free to use sentences or a bulleted list.

- Loaded Google Maps Javascript API library
- Created new component to autocomplete location search
- In RegisterPage, we geocoded coordinates of the address passed in by the component (child)
- In ProfilePage's edit view, we did the same
- Made it so that the location input changes when the searched address is clicked

## Testing

Explain how you tested these changes (unit tests, manual UI testing, etc.) or N/A if testing is not necessary (and explain why).

N/A

2020-11-29 22:39 UTC, rrrliu requested changes
awesome!! the autocomplete + map works v nicely :^). couple things:
1. merge with `main` to resolve merge conflicts and so that the diff will be up-to-date
2. don't expose environment variables on github
3. can we have the font and styling of the autocomplete list match that of our app? it should be more similar to how our dropdown looks in Filter
<img width="484" alt="image" src="https://user-images.githubusercontent.com/36896271/100555405-1bcb1a80-3250-11eb-8c4f-026972d20b21.png">
filter dropdown:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/36896271/100555487-a3b12480-3250-11eb-87dc-f0d2e7502e0b.png">

2020-11-29 22:39 UTC, rrrliu commented on .gitignore
> +# .env
why is this commented out?

2020-11-29 22:39 UTC, rrrliu commented on .env
> +SESSION_ID = keyboard cat
never check in .env files, please `git rm --cached` this file

2020-11-30 05:07 UTC, rrrliu commented on client/src/components/Autocomplete/LocationSearchInput.js
> +                    key="loveliness"
lovely, but key should be unique for each element in a map. use the index as the key

2020-11-30 07:32 UTC, leebianca submitted a review, later dismissed

2020-11-30 08:21 UTC, rrrliu approved these changes

2020-12-01 03:34 UTC, merged