Card component
codebase-berkeley/cofed pull request #6
Opened 2020-10-16 05:23 UTC by ehao1

Use CardComponentTester.js to see the CardComponent (copy and paste into App.js).

CardComponent is a container composed of two sub-containers:
The first sub-container holds the Co-Op profile picture, name, and location.
The second sub-container holds the Co-Op tags. 

Specifically, to help with the creation of the Co-Op tags, we created a Tag function which takes in array of strings as input and outputs Tag Components

2020-10-16 21:17 UTC, rrrliu requested changes
This looks sooo good and the tags are so responsive! Love it :)

<img width="520" alt="image" src="https://user-images.githubusercontent.com/36896271/96307203-107ca200-0fb6-11eb-813c-5b117e8b693a.png">

Left some comments below, let me know if anything is confusing! Also make sure to update `npm` to `yarn` as per the recent Slack message.

2020-10-16 21:17 UTC, rrrliu commented on client/package-lock.json
> +{
sorry for miscommunicating, but delete this file since we're using `yarn` now (see message on slack)

2020-10-16 21:17 UTC, rrrliu commented on client/src/CardComponent.css
> +  export default App; */
try to remove commented code before you commit (I think you already have this is `CardComponentTester.js`)

2020-10-16 21:17 UTC, rrrliu commented on client/src/CardComponent.css
> +}
use classes instead of ids since we'll be having multiple `CardComponent`s per page

2020-10-16 21:17 UTC, rrrliu commented on client/src/CardComponent.js
> +//   );
same here, remove all commented code that's not documentation

2020-10-16 21:17 UTC, rrrliu commented on client/src/CardComponent.css
> +  margin-left: 300px;
why is this `300px`?

2020-10-16 21:17 UTC, rrrliu commented on client/src/Tag.css
> +  /* background-color: #1949aa; */
remove

2020-10-17 04:33 UTC, leebianca requested changes
WOW it looks amazing!! Just left a few comments here and there

2020-10-17 04:33 UTC, leebianca commented on client/src/Tag.css
> +  padding: 4px 22px 4px 22px;
simplify to `padding: 4px 22px;`

2020-10-17 04:33 UTC, leebianca commented on client/src/CardComponentTester.js
> +/* Copy and paste this ENTIRE FILE into App.js
What's the difference between this file and `CardComponent`? Can we remove one of them since they're identical?

2020-10-17 04:33 UTC, leebianca commented on client/src/CardComponent.css
> +  margin-top: 12px;
Let's combine all the margin css here in one line with `margin: 12px 0 22px 20px;`and let's also add a `margin-right` to this container (and the name and location containers) so that the tags don't get too close to the edge of the box when the box resizes.

This case for example.
<img width="456" alt="Screen Shot 2020-10-16 at 8 07 10 PM" src="https://user-images.githubusercontent.com/20432204/96327088-412afe80-0feb-11eb-9bf6-3eec2acfe361.png">

2020-10-17 05:28 UTC, leebianca commented on client/src/CardComponent.js
> +          {props.tags.map((text) => (
Oh also, let's add a null check for `props.tags` so that it doesn't error in the case that there aren't any `tag`s.

2020-10-18 05:39 UTC, rrrliu approved these changes

2020-10-18 05:39 UTC, leebianca approved these changes

2020-10-18 05:40 UTC, merged